name: Documentation Check

on:
  push:
  pull_request:

jobs:
  check-markdown:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: './.markdownlint.jsonc'
          args: './docs'

  check-markdown-examples:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v
      - name: Build V
        run: cd v && make && sudo ./v symlink && cd -
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          path: docs
      - name: Check markdown line length && code examples
        run: v check-md -hide-warnings ./docs
