name: Documentation Check

on:
  push:
  pull_request:

jobs:
  check-markdown:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: './.markdownlint.jsonc'
          args: './docs'

  check-markdown-examples:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Build V
        working-directory: ./v
        run: make
      - name: Check markdown line length && code examples
        working-directory: ./v
        run: ./v check-md -hide-warnings ../docs
